version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: twitterclone_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - mysql

    mysql:
        image: mysql:8
        container_name: twitterclone_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - laravel

    nginx:
        image: nginx:stable
        container_name: twitterclone_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel
        depends_on:
            - app

networks:
    laravel:
        driver: bridge
