version: '3'

services:
    app:
        image: ${IMAGE_NAME:-oiseaubleuc/herexamentwi}:${IMAGE_TAG:-latest}
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./storage:/var/www/html/storage
            - ./database:/var/www/html/database
        environment:
            APP_ENV: ${APP_ENV:-local}
            APP_DEBUG: ${APP_DEBUG:-true}
            APP_KEY: ${APP_KEY:-base64:EddjxJdefepiBcRRe/1PoS8OhH9L0SaGWo4Yb8hNwuM=}
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
            CACHE_DRIVER: file
            SESSION_DRIVER: file
            QUEUE_CONNECTION: sync
        networks:
            - mini-twitter

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "${HTTP_PORT:-8000}:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - mini-twitter

networks:
    mini-twitter:
        driver: bridge
