apiVersion: v1
kind: Secret
metadata:
  name: mini-twitter-secrets
  namespace: mini-twitter
type: Opaque
data:
  APP_KEY: "YmFzZTY0OkVkZGp4SmRlZmVwaUJjUlJlLzFQb1M4T2hIOUwwU2FHV280WWI4aE53dU09"
  DB_DATABASE: "L3Zhci93d3cvaHRtbC9kYXRhYmFzZS9kYXRhYmFzZS5zcWxpdGU="
