apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mini-twitter-db-pvc
  namespace: mini-twitter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
