name: CI - Tests (SQLite)

on:
  push:
    branches: [ "main" ]


env:
  PROJECT_DIR: .

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo_sqlite, mbstring, bcmath, intl
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles(format('{0}/composer.lock', env.PROJECT_DIR)) }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Write .env.testing (SQLite in-memory)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          cat > .env.testing <<'ENV'
          APP_ENV=testing
          APP_KEY=base64:Q7wXtO8a3dRQHq5IM4NsPZ8MthM4T0DyQw5sV0D9Nl8=
          APP_DEBUG=true
          LOG_CHANNEL=stack
          CACHE_DRIVER=array
          SESSION_DRIVER=array
          QUEUE_CONNECTION=sync
          DB_CONNECTION=sqlite
          DB_DATABASE=:memory:
          ENV

      - name: Run tests
        working-directory: ${{ env.PROJECT_DIR }}
        run: php artisan test --env=testing -v

