name: tesing

on:
  push:
    branches: [ main ]

jobs:
  tests:
    name: Laravel (dev)
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ${{ github.workspace }}/database/database.sqlite
      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      MAIL_MAILER: array

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_sqlite, mbstring, bcmath
          tools: composer
          coverage: none

      - name: Install Composer dependencies (cached)
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Dump autoload
        run: composer dump-autoload -o

      - name: Prepare .env & key
        run: |
          cp -n .env.example .env || true
          php artisan key:generate --force

      - name: Create SQLite file
        run: |
          mkdir -p database
          rm -f database/database.sqlite
          touch database/database.sqlite

      - name: Fresh migrate (sqlite) + seed
        run: php artisan migrate:fresh --seed --force --database=sqlite

      - name: Show migration status
        run: php artisan migrate:status --database=sqlite

      - name: Run tests
        run: php artisan test --without-tty
