name: CI (Laravel Build & Test)

on:
  pull_request:
    branches: [ main ]   # PR's die naar main gaan
  push:
    branches: [ main ]   # directe pushes op main
  workflow_dispatch:      # handmatig starten (optioneel)

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ${{ github.workspace }}/database/database.sqlite
      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'      # zet desnoods op '8.3' als jij dat gebruikt
          extensions: mbstring, bcmath, pdo_sqlite
          coverage: none
          tools: composer

      - name: Install Composer dependencies (cached)
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Prepare .env & app key
        run: |
          cp -n .env.example .env || true
          php artisan key:generate --force

      - name: Prepare SQLite database
        run: |
          mkdir -p database
          rm -f database/database.sqlite
          touch database/database.sqlite

      - name: Migrate
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --without-tty
