name: tesing

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Laravel (dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_sqlite, mbstring, bcmath
          tools: composer
          coverage: none

      - name: Install Composer dependencies (cached)
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Dump autoload
        run: composer dump-autoload -o

      - name: Prepare .env & key
        run: |
          cp -n .env.example .env || true
          php artisan key:generate --force

      - name: Prepare SQLite database
        run: |
          mkdir -p database
          rm -f database/database.sqlite
          touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --force


      - name: Run tests
        run: php artisan test --without-tty

