name: SQL Testing
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      APP_URL: http://localhost
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
      QUEUE_CONNECTION: sync
      MAIL_MAILER: log
      SESSION_DRIVER: array
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_sqlite, sqlite3
          tools: composer:v2

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare app
        run: |
          cp .env.example .env
          php artisan key:generate
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --force

      - name: Run tests
        run: php artisan test -q
