name: Docker Push (simple)

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare baseline SQLite
        run: |
          cp .env.example .env
          php artisan key:generate
          mkdir -p database
          # baseline database.sqlite die we migreren
          touch database/database.sqlite
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's|^DB_DATABASE=.*|DB_DATABASE='$(pwd)'/database/database.sqlite|' .env

      - name: Migrate baseline
        run: php artisan migrate --force

      - name: Run tests (parallel)
        run: php artisan test --parallel --recreate-databases




