name: SQL Testing
on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_sqlite, sqlite3
          tools: composer:v2

      - name: Install deps
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Prepare database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --force

      - name: Run tests
        run: php artisan test -q
